export const SET_TASKS = "SET_TASKS";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const SET_CURRENT_TASK_INFO = "SET_CURRENT_TASK_INFO";
export const SET_DAILY_TASKS = "SET_DAILY_TASKS";
export const CHANGE_TASK_PROP_SUCCESS = "CHANGE_TASK_PROP_SUCCESS";