export const SET_ROLES = "SET_ROLES";
export const SET_PRIVILEGES = "SET_PRIVILEGES";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const ADD_PRIVILEGE_TO_ROLE = "ADD_PRIVILEGE_TO_ROLE";
export const REMOVE_PRIVILEGE_FROM_ROLE = "REMOVE_PRIVILEGE_FROM_ROLE";
