export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_NOTIFICATION_STATUS_SUCCESS = 'SET_NOTIFICATION_STATUS_SUCCESS';
export const SET_INVITATION_SUCCESS = 'SET_INVITATION_SUCCESS';
