export const SET_BOARD_DATA = "SET_BOARD_DATA";
export const ADD_COLUMN_SUCCESS = "ADD_COLUMN_SUCCESS";
export const ADD_TASK_TO_COLUMN_SUCCESS = "ADD_TASK_TO_COLUMN_SUCCESS";
export const COLUMN_REORDER = "COLUMN_REORDER";
export const TASK_REORDER = "TASK_REORDER";
export const TASK_MOVED = "TASK_MOVED";
export const DATA_FETCHED = "DATA_FETCHED";
