export const SET_USER_FULL_DATA = "SET_USER_FULL_DATA";
export const SET_SEARCHED_USERS = "SET_SEARCHED_USERS";
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_FB_TOKEN = 'SET_FB_TOKEN';
export const SET_BOARD_USERS = "SET_BOARD_USERS";
export const CHANGE_USER_ROLE_SUCCESS = "CHANGE_USER_ROLE_SUCCESS";
